### crides per a testing ràpid d'endpoints
POST http://localhost:8080/api/users/register?userType=Estudiant
Content-Type: application/json

{
  "mail": "ivan.fernandez@example.com",
  "name": "Ivan Fernandez"
}

###

###
GET http://localhost:8080/api/users/signIn?mail=ivan.fernandez@example.com

### Comprobar que la disponbilitat s'actualitza correctament
POST http://localhost:8080/api/docent/disponibilitat
Content-Type: application/json

[
  { "timestamp": "2026-06-01T08:00:00" },
  { "timestamp": "2026-06-01T09:00:00" },
  { "timestamp": "2026-06-01T10:00:00" },
  { "timestamp": "2026-06-01T11:00:00" },
  { "timestamp": "2026-06-01T12:00:00" },
  { "timestamp": "2026-06-01T13:00:00" },
  { "timestamp": "2026-06-01T15:00:00" },
  { "timestamp": "2026-06-01T16:00:00" },
  { "timestamp": "2026-06-01T17:00:00" },
  { "timestamp": "2026-06-01T18:00:00" },
  { "timestamp": "2026-06-01T19:00:00" },

  { "timestamp": "2026-06-02T08:00:00" },
  { "timestamp": "2026-06-02T09:00:00" },
  { "timestamp": "2026-06-02T10:00:00" },
  { "timestamp": "2026-06-02T11:00:00" },
  { "timestamp": "2026-06-02T12:00:00" },
  { "timestamp": "2026-06-02T13:00:00" },
  { "timestamp": "2026-06-02T15:00:00" },
  { "timestamp": "2026-06-02T16:00:00" },
  { "timestamp": "2026-06-02T17:00:00" },
  { "timestamp": "2026-06-02T18:00:00" },
  { "timestamp": "2026-06-02T19:00:00" },

  { "timestamp": "2026-06-03T08:00:00" },
  { "timestamp": "2026-06-03T09:00:00" },
  { "timestamp": "2026-06-03T10:00:00" },
  { "timestamp": "2026-06-03T11:00:00" },
  { "timestamp": "2026-06-03T12:00:00" },
  { "timestamp": "2026-06-03T13:00:00" },
  { "timestamp": "2026-06-03T15:00:00" },
  { "timestamp": "2026-06-03T16:00:00" },
  { "timestamp": "2026-06-03T17:00:00" },
  { "timestamp": "2026-06-03T18:00:00" },
  { "timestamp": "2026-06-03T19:00:00" },

  { "timestamp": "2026-06-04T08:00:00" },
  { "timestamp": "2026-06-04T09:00:00" },
  { "timestamp": "2026-06-04T10:00:00" },
  { "timestamp": "2026-06-04T11:00:00" },
  { "timestamp": "2026-06-04T12:00:00" },
  { "timestamp": "2026-06-04T13:00:00" },
  { "timestamp": "2026-06-04T15:00:00" },
  { "timestamp": "2026-06-04T16:00:00" },
  { "timestamp": "2026-06-04T17:00:00" },
  { "timestamp": "2026-06-04T18:00:00" },
  { "timestamp": "2026-06-04T19:00:00" },

  { "timestamp": "2026-06-05T08:00:00" },
  { "timestamp": "2026-06-05T09:00:00" },
  { "timestamp": "2026-06-05T10:00:00" },
  { "timestamp": "2026-06-05T11:00:00" },
  { "timestamp": "2026-06-05T12:00:00" },
  { "timestamp": "2026-06-05T13:00:00" },
  { "timestamp": "2026-06-05T15:00:00" },
  { "timestamp": "2026-06-05T16:00:00" },
  { "timestamp": "2026-06-05T17:00:00" },
  { "timestamp": "2026-06-05T18:00:00" },
  { "timestamp": "2026-06-05T19:00:00" },

  { "timestamp": "2026-06-06T08:00:00" },
  { "timestamp": "2026-06-06T09:00:00" },
  { "timestamp": "2026-06-06T10:00:00" },
  { "timestamp": "2026-06-06T11:00:00" },
  { "timestamp": "2026-06-06T12:00:00" },
  { "timestamp": "2026-06-06T13:00:00" },
  { "timestamp": "2026-06-06T15:00:00" },
  { "timestamp": "2026-06-06T16:00:00" },
  { "timestamp": "2026-06-06T17:00:00" },
  { "timestamp": "2026-06-06T18:00:00" },
  { "timestamp": "2026-06-06T19:00:00" },

  { "timestamp": "2026-06-07T08:00:00" },
  { "timestamp": "2026-06-07T09:00:00" },
  { "timestamp": "2026-06-07T10:00:00" },
  { "timestamp": "2026-06-07T11:00:00" },
  { "timestamp": "2026-06-07T12:00:00" },
  { "timestamp": "2026-06-07T13:00:00" },
  { "timestamp": "2026-06-07T15:00:00" },
  { "timestamp": "2026-06-07T16:00:00" },
  { "timestamp": "2026-06-07T17:00:00" },
  { "timestamp": "2026-06-07T18:00:00" },
  { "timestamp": "2026-06-07T19:00:00" },

  { "timestamp": "2026-06-08T08:00:00" },
  { "timestamp": "2026-06-08T09:00:00" },
  { "timestamp": "2026-06-08T10:00:00" },
  { "timestamp": "2026-06-08T11:00:00" },
  { "timestamp": "2026-06-08T12:00:00" },
  { "timestamp": "2026-06-08T13:00:00" },
  { "timestamp": "2026-06-08T15:00:00" },
  { "timestamp": "2026-06-08T16:00:00" },
  { "timestamp": "2026-06-08T17:00:00" },
  { "timestamp": "2026-06-08T18:00:00" },
  { "timestamp": "2026-06-08T19:00:00" },

  { "timestamp": "2026-06-09T08:00:00" },
  { "timestamp": "2026-06-09T09:00:00" },
  { "timestamp": "2026-06-09T10:00:00" },
  { "timestamp": "2026-06-09T11:00:00" },
  { "timestamp": "2026-06-09T12:00:00" },
  { "timestamp": "2026-06-09T13:00:00" },
  { "timestamp": "2026-06-09T15:00:00" },
  { "timestamp": "2026-06-09T16:00:00" },
  { "timestamp": "2026-06-09T17:00:00" },
  { "timestamp": "2026-06-09T18:00:00" },
  { "timestamp": "2026-06-09T19:00:00" }
]

### Treure tota la disponibilitat
GET http://localhost:8080/api/tribunal/disponbilitats

### Treure totes les experteses
GET http://localhost:8080/api/tribunal/experteses

### Importació de l'excel de prova
POST http://localhost:8080/api/tribunal/import
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="Tutors_TFG_20242025.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< D:\GitHub\TFG_2026_IvanFernandez\tribunals-backend\src\test\java\org\example\tribunalsbackend\Tutors_TFG_20242025.xlsx
------WebKitFormBoundary--

### Organitzar els tribunals
GET http://localhost:8080/api/tribunal/organitzar?maxClassrooms=2

### Obtenir els tribunals organitzats
GET  http://localhost:8080/api/tribunal/all

### Obtenir els detalls d'un estudiant
GET http://localhost:8080/api/estudiant/tfg?mail=ahernandezm@edu.tecnocampus.cat

### Obtenir els detalls d'un docent
GET http://localhost:8080/api/docent/details?mail=barberan@tecnocampus.cat

### Editar informació d'un docent
PUT http://localhost:8080/api/docent/update
Content-Type: application/json

{
  "name": "Pere Barberán",
  "mail": "barberan@tecnocampus.cat",
  "veteran": true,
  "experteses": [
    "Desenvolupament d’aplicacions informàtiques",
    "Tractament del Senyal"
  ],
  "disponibilitat": [
    "2026-07-06T08:00:00",
    "2026-07-06T09:00:00",
    "2026-07-06T10:00:00"
  ]
}